# Numpy experiments

Import numpy package.

In [1]:
import numpy as np

## Reshaping

Optionally, the last index given in `reshape` can be `-1`, the shape will be such that the dimensions multiply to the size of the original array.

In [ ]:
a = np.arange(1, 21, dtype=np.int).reshape(4, -1)
a

In three dimensions, the last dimension can be replaced by `-1`.

In [ ]:
b = a.reshape(2, 5, -1)
b

## Slicing

Define 3D data with a "width" of 5, a "height" of 4, and a "depth" of 3.

In [2]:
a = np.arange(1, 61, dtype=np.int).reshape((3, 4, -1))

When the last dimension is -1, it is computed automatically if possible, i.e., if the product of the sizes in each dimension is the size of the array.

In [3]:
a.shape

(3, 4, 5)

When data is viewed as 3D, slice the "front" layer.

In [ ]:
a[0, :, :]

Slice the middle layer.

In [ ]:
a[1, :, :]

Slice the back layer.

In [ ]:
a[2, :, :]

Slice the top layer (first row is front).

In [ ]:
a[:, 0, :]

Slice the left layer (first row is front).

In [ ]:
a[:, :, 0]

Introducing new leading dimension.

In [ ]:
a[None].shape

Check that this is the original matrix, with size of leading dimension equal to 1.

In [ ]:
np.all(a == a[None][0])

Add additional "last" dimension, check that the result is the top-front row, with each element in an individual dimension 1 subarray.

In [ ]:
a[:, :, :, None][0, 0]

It is important to realize that slicing doesn't copy, i.e., a slice yields a reference to the original data. Consider the following matrix.

In [11]:
b = np.arange(1, 21).reshape(4, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
c = b[1:-1, 1:-1]
c

array([[ 7,  8,  9],
       [12, 13, 14]])

Now we modify an element of `c`

In [13]:
c[0, 0] = 0
c

array([[ 0,  8,  9],
       [12, 13, 14]])

Clearly, `c` was changed, but so is `b`.

In [14]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Fancy indexing

Create a new $4 \times 5$ array.

In [ ]:
a = np.arange(1, 21, dtype=np.int).reshape((4, -1))
a

Select the second and fourth row.

In [ ]:
a[[1, 3], :]

Select the first and fourth column.

In [ ]:
a[:, [0, 3]]

## Structured arrays

Although strictly speaking not fancy indexing, we can create structured arrays, which you can think of as arrrays of structures. These arrays can be indexed by number, and by structure field name.

In [80]:
b = np.zeros(10, dtype={'names': ('x', 'y'), 'formats': ('f8', 'f8')})
b

array([(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.),
       (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
      dtype=[('x', '<f8'), ('y', '<f8')])

Each element acts as a tuple, the first field has name `x` and type `np.float`, the second has name `y`, and is also `np.float`.

The shape shows it is an 1-D array.

In [81]:
b.shape

(10,)

The type of the elements is perhaps a bit surprising.

In [86]:
type(b[0])

numpy.void

We can initialize the `x` and `y` fields of each array element with a single assingment.

In [82]:
b['x'] = np.random.uniform(size=10)
b['y'] = np.random.uniform(size=10)
b

array([(0.26915628, 0.5274105 ), (0.04049963, 0.1217886 ),
       (0.11351208, 0.21175945), (0.91944209, 0.8435622 ),
       (0.03580187, 0.79442088), (0.9349676 , 0.360445  ),
       (0.94119875, 0.49322986), (0.08632289, 0.96568537),
       (0.78933495, 0.50620139), (0.61599756, 0.85082955)],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [85]:
b['x']

array([0.26915628, 0.04049963, 0.11351208, 0.91944209, 0.03580187,
       0.9349676 , 0.94119875, 0.08632289, 0.78933495, 0.61599756])

Using a numerical index gives the corresponding element in the array.

In [83]:
b[0]

(0.26915628, 0.5274105)

Accessing elements by field number or field name is equivalent.

In [84]:
b[4][1] == b[4]['y']

True

## Stacking

Create two matrices, both $4 \times 5$.

In [ ]:
a = np.arange(1, 21, dtype=np.int).reshape((4, -1))
b = np.arange(21, 41, dtype=np.int).reshape((4, -1))
print(a)
print(b)

Stack matrices horizontally.

In [ ]:
np.hstack((a, b))

Stack matrices vertically.

In [ ]:
np.vstack((a, b))

Create a list of 3 arrays, each $4 \times 5$.

In [ ]:
arrays_2d = []
size_2d = 20
for i in range(3):
    upperleft = i*size_2d + 1
    arrays_2d.append(np.arange(upperleft, upperleft + size_2d, dtype=np.int).reshape(4, -1))

Create a 3D array out of the list of 2D arrays.

In [ ]:
array_3d = np.array(arrays_2d)

array_3d.shape

Get front plane.

In [ ]:
array_3d[0, :, :]

Get top plane.

In [ ]:
array_3d[:, 0, :]